name: Releases

on: 
  push:
    tags:
    - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Build
      run: VERSION="${{ github.ref_name }}" make release

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "bin/*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}